### ISSUE TITLE
Removing display lines segfaults deadbeef

### ISSUE THREAD

**Issue by skrinakron** [cboxdoerfer/ddb_playback_status#4]
In a GTK2 deadbeef 1.8.0, a fresh clone of ddb_playback_status built with `make gtk2` makes deadbeef crash with a segmentation fault when the number of displayed lines is reduced.

Steps taken (scenario 1):
1. Right-click on the playback status widget and select "Configure".
2. Reduce the number of lines from 3 to 2. The text box with album and artist information disappears.
3. Click "Apply" and "OK"; the crash may occur on either of these. Deadbeef segfaults.

Steps taken (scenario 2):
1. Right-click on the playback status widget and select "Configure".
2. Reduce the number of lines to 1.
3. Click "Apply" and "OK". Deadbeef segfaults.
4. Restart deadbeef and go back to the playback status configuration. The number of lines is 1 but 10 text boxes are displayed.

In both cases deadbeef crashes with a SIGSEGV to thread 1 (gtkui). Here's a gdb backtrace of the crashing thread from a deadbeef and ddb_playback_status built with debugging information:
```
Thread 1 (Thread 0x7ffff7fcbb80 (LWP 25033)):
#0  0x00007ffff72d605c in raise () from /lib64/libc.so.6
#1  0x00007ffff72d79d1 in abort () from /lib64/libc.so.6
#2  0x00007ffff731c230 in ?? () from /lib64/libc.so.6
#3  0x00007ffff73241e9 in ?? () from /lib64/libc.so.6
#4  0x00007ffff73252dc in ?? () from /lib64/libc.so.6
#5  0x00007ffff41087fc in ?? () from /usr/lib64/libglib-2.0.so.0
#6  0x00007ffff410b7f8 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#7  0x00007ffff410ba38 in ?? () from /usr/lib64/libglib-2.0.so.0
#8  0x00007ffff410bd72 in g_main_loop_run () from /usr/lib64/libglib-2.0.so.0
#9  0x00007ffff629f0bf in gtk_main () from /usr/lib64/libgtk-x11-2.0.so.0
#10 0x00007ffff680a8db in gtkui_thread (ctx=0x0) at gtkui.c:1404
#11 0x00007ffff680b09d in gtkui_start () at gtkui.c:1527
#12 0x0000555555589f5e in main (argc=1, argv=0x7fffffffded8) at main.c:1229
```

**Comment by skrinakron** [comment]
Since much of the backtrace is in libraries, these are the versions of the libraries involved:
* GTK+ 2.24.32
* GLib 2.58.3
* glibc 2.29
